name: CI - Spring Boot
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    uses: ./.github/workflows/reutilizable-build.yml
    with:
      java-version: '25'
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code # Compilación del proyecto
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build and test with Maven # Pruebas unitarias
        run: mvn clean package -DskipTests

      - name: Run static code analysis (optional)
        run: mvn sonar:sonar -Dsonar.projectKey=WinTux_20250819j -Dsonar.organization=wintux-1 -Dsonar.host.url=https://sonarcloud.io
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: springboot-app
          path: target/*.jar
      - name: Download JAR
        uses: actions/download-artifact@v3
        with:
          name: springboot-app
