name: Maven Package

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn clean package
    - name: Listar paquetes
      run: find . -type f -name "*.jar"
    - name: Upload de paquetes
      uses: actions/upload-artifact@v4
      with:
        name: springboot-modules
        path: |
          producto-service/target/*.jar
          orden-service/target/*.jar
          servidor-eureka/target/*.jar
          servidor-config/target/*.jar
          inventario-service/target/*.jar
    - name: Download de los JARs
      uses: actions/download-artifact@v4
      with:
        name: springboot-modules
        path: ./jars
    - name: Mostrando los JARs descargados
      run: ls -R ./jars
    - name: Creando Release GitHub
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.1.0
        release_name: "Release v1.1.0"
        draft: false
        prerelease: false
    - name: Subir producto-service como asset
#      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        for archivo in ./jars/*.jar; do
          echo "Subiendo $archivo"
          gh release upload v1.1.0 "$archivo" --clobber
        done
#      with:
#        upload_url: ${{ steps.create_release.outputs.upload_url }}
#        asset_path: ./producto-service/target/producto-service-0.0.1-SNAPSHOT.jar
#        asset_name: producto-service.jar
#        asset_content_type: application/java-archive
